path=./cmd/server/
filename=main.go
appname=caching-proxy

run:
	go run ${path}${filename}
build-window:
	go build -o ${appname}.exe ${path}${filename}
build:
	go build -o ${appname} ${path}${filename}